Feature: Manage a Hacknet node network to make profits

  Rule: If there is no Hacknet node, create one with external investment

    Rule: Improve the Hacknet network profitability once the previous investment is profitable




  Rule: An Hacknet investment is said profitable once it has generated enough profits
    Enough profits means that the last investment has been refund by the network and the network has generate at least
    x time its value

    Rule: Upgrade the component of the network that will lead to the maximum profit over time

  Rule: An upgrade can be done only with profits generated by the Hacknet network

    Scenario: If there is no Hacknet node, create one with external investment



  Rule: An upgrade is profitable once the upgrade node has been able to refund its upgrade and to save for the next one


